version: '3.8'
services:
  db:
    image: mysql:8
    container_name: flashcards_db
    restart: always
    ports:
      - "${MYSQL_HOST_PORT:-3010}:3306"
    environment:
      MYSQL_DATABASE:      ${MYSQL_DATABASE:-flashcards_db}
      MYSQL_USER:          ${MYSQL_USER:-devuser}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD:-devpass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-devroot}
    volumes:
      - mysqldata:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: flashcards_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - miniodata:/data

volumes:
  mysqldata:
  miniodata:
